name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        idf_ver: ["latest"]
        example: ["simple-ethernet", "iperf", "tcp_server"]
        idf_target: ["esp32"]
    runs-on: ubuntu-20.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - name: Checkout esp_eth_drivers
        uses: actions/checkout@master
        with:
          path: esp_eth_drivers
      - name: Build ${{ matrix.example }} with IDF-${{ matrix.idf_ver }} for ${{ matrix.idf_target }} with ${{ matrix.eth_target }}
        env:
          IDF_TARGET: ${{ matrix.idf_target }}
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          pip install idf-build-apps
          cd $GITHUB_WORKSPACE/esp_eth_drivers/common_examples/${{ matrix.example }}
          idf-build-apps build -p . --target ${{ matrix.idf_target }} --build-dir build_@t_@w --config 'sdkconfig.defaults.*='